// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlomilasjV2zmp0xrszLxKnGa9ke-4oak',
    appId: '1:411220272299:web:b78edf91c6c9c72b7e83ee',
    messagingSenderId: '411220272299',
    projectId: 'navithesia',
    authDomain: 'navithesia.firebaseapp.com',
    storageBucket: 'navithesia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIvjEVNzlhmOqz9zm-kZpxFGSb_VWtXI',
    appId: '1:411220272299:android:782f0f6f7a600aad7e83ee',
    messagingSenderId: '411220272299',
    projectId: 'navithesia',
    storageBucket: 'navithesia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyVgzYgMZL2xCAFNvXvICflUGaOK7agag',
    appId: '1:411220272299:ios:30ba76fef2415d1a7e83ee',
    messagingSenderId: '411220272299',
    projectId: 'navithesia',
    storageBucket: 'navithesia.firebasestorage.app',
    iosBundleId: 'com.navithesia.navithesiaBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyVgzYgMZL2xCAFNvXvICflUGaOK7agag',
    appId: '1:411220272299:ios:30ba76fef2415d1a7e83ee',
    messagingSenderId: '411220272299',
    projectId: 'navithesia',
    storageBucket: 'navithesia.firebasestorage.app',
    iosBundleId: 'com.navithesia.navithesiaBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlomilasjV2zmp0xrszLxKnGa9ke-4oak',
    appId: '1:411220272299:web:28636fa1d09e65997e83ee',
    messagingSenderId: '411220272299',
    projectId: 'navithesia',
    authDomain: 'navithesia.firebaseapp.com',
    storageBucket: 'navithesia.firebasestorage.app',
  );
}
